image: hiono/texlive

stages:
    - uebungen
    - slides
    - collect

uebung:komplett:
    stage: uebungen
    tags:
        - docker
    script:
        - cd uebungen
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" Uebung-komplett.tex
    artifacts:
        untracked: true
        expire_in: 1 week

uebung:physik:
    stage: uebungen
    tags:
        - docker
    script:
        - cd uebungen
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" Uebung-Physik.tex
    artifacts:
        untracked: true
        expire_in: 1 week

uebung:mathe:
    stage: uebungen
    tags:
        - docker
    script:
        - cd uebungen
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" Uebung-Mathe.tex
    artifacts:
        untracked: true
        expire_in: 1 week


slides:komplett:
    stage: slides
    tags:
        - docker
    dependencies:
        - uebung:komplett
    script:
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" presentation-Komplett.tex
    artifacts:
        untracked: true
        expire_in: 1 week


slides:mathe:slides:
    stage: slides
    tags:
        - docker
    dependencies:
        - uebung:komplett
    script:
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" presentation-mathe-slides.tex
    artifacts:
        untracked: true
        expire_in: 1 week


slides:physik:handout:
    stage: slides
    tags:
        - docker
    dependencies:
        - uebung:physik
    script:
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" presentation-Physik-Handout.tex
    artifacts:
        untracked: true
        expire_in: 1 week

slides:physik:slides:
    stage: slides
    tags:
        - docker
    dependencies:
        - uebung:physik
    script:
        - latexmk -pdf -pdflatex="pdflatex -interaction=nonstopmode %O %S" presentation-Physik-Slides.tex
    artifacts:
        untracked: true
        expire_in: 1 week


collector:
    stage: collect
    tags:
        - docker
    script: echo OK
    environment: production
    artifacts:
        paths:
            - presentation-*.pdf
            - uebungen/Uebung-*.pdf
