#!/bin/bash

function build {
    for f in *.tex
      do
        latexmk -pdf $f
    done
	rm *.aux
	rm *.fdb_latexmk
	rm *.fls
	rm *.log
	rm *.nav
	rm *.out
	rm *.snm
	rm *.toc
	rm *.vrb
	rm *.vls
	rm *.bbl
	rm *.bcf
	rm *.blg
	rm *.xml
}

cd uebungen
build
cd ..
build
